name: Test Airtable API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call Airtable API
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_BASE_NAME: ${{ secrets.AIRTABLE_BASE_NAME }}
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
        run: |
          echo "Calling Airtable..."

          # 1) 清理 Base ID 的 CR/LF，避免 URL 中間被斷行
          BASE_ID_CLEAN=$(printf '%s' "$AIRTABLE_BASE_ID" | tr -d '\r\n')

          # 2) 將表格名稱做 URL 編碼（支援中文／空白／特殊字元）
          TABLE_ENC=$(printf '%s' "$AIRTABLE_BASE_NAME" | jq -sRr '@uri')

          # 3) 組 URL
          URL="https://api.airtable.com/v0/${BASE_ID_CLEAN}/${TABLE_ENC}?maxRecords=1"
          echo "URL(only for debug; parts may be masked)=$URL"

          # 4) 呼叫 Airtable API
          curl -sS "$URL" \
            -H "Authorization: Bearer $AIRTABLE_TOKEN" \
            -H "Content-Type: application/json" \
          | jq '.'

