name: Test Airtable API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call Airtable API
        env:
          AIRTABLE_TOKEN:      ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID:    ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID:   ${{ secrets.AIRTABLE_TABLE_ID }}   # <- 新增這個
        run: |
          echo "Calling Airtable..."

          # 清掉可能混入的 CR/LF
          BASE_ID_CLEAN=$(printf '%s' "$AIRTABLE_BASE_ID"  | tr -d '\r\n')
          TABLE_ID_CLEAN=$(printf '%s' "$AIRTABLE_TABLE_ID" | tr -d '\r\n')

          URL="https://api.airtable.com/v0/${BASE_ID_CLEAN}/${TABLE_ID_CLEAN}?maxRecords=1"
          echo "URL(only for debug; parts may be masked)=$URL"

          curl -sS "$URL" \
            -H "Authorization: Bearer $AIRTABLE_TOKEN" \
            -H "Content-Type: application/json" \
          | jq '.'
