name: Test Airtable API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call Airtable API
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_BASE_NAME: ${{ secrets.AIRTABLE_BASE_NAME }}
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
        run: |
            echo "Calling Airtable..."
            curl -v "https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${AIRTABLE_BASE_NAME}?maxRecords=1" \
              -H "Authorization: Bearer $AIRTABLE_TOKEN" \
              -H "Content-Type: application/json" \
             | jq '.'
